services:
  web:
    build:
      context: .
    ports:
      - 9000:9000
    volumes:
      - ".:/var/www/html"
    command: php -S 0.0.0.0:9000
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db-data:
