services:
  web:
    build:
      context: .
    ports:
      - 9000:9000
    volumes:
      - ".:/var/www/html"
    command: php -S 0.0.0.0:9000 -t public
    extra_hosts:
      - host.docker.internal:host-gateway
